version: '3.7'
services:
  php:
    build: .
    container_name: php-container
    volumes:
      - .:/var/www/html
    ports:
      - "8080:8080"
    entrypoint: ["/bin/sh", "-c", "composer install && php -S 0.0.0.0:8080"]
